# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: meeting-front-end

frameworkVersion: '3'

configValidationMode: error

plugins:
  - serverless-finch


# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
  stage: dev
  memorySize: 256


custom:
  siteName: ${param:siteName}
  client:
    bucketName: ${self:custom.siteName}
    distributionFolder: ../dist/frontend
    indexDocument: index.html
    errorDocument: index.html
    corsFile: cors.json

params:
  prod:
    siteName: meeting.webtradepay.au
    version: "v1"
  dev:
    siteName: dev-meeting.webtradepay.au
    version: "v1-dev"

resources:
  Resources:

    StaticSite:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:custom.client.bucketName}
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html

    # specifying the policies to make sure all files inside the Bucket are avaialble
    WebAppS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticSite
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
              - s3:GetObject
              Resource: arn:aws:s3:::${self:custom.client.bucketName}/*
